### ISSUE TITLE
Bitbucket markdown

### ISSUE THREAD

**Issue by fynman** [maxtoroq/sandcastle-md#3]
Hi,

  Bitbucket doesn't render "![Public class]" correctly, only text is shown, no icon.

  Where in the source can I change this?

Thanks,
Bart

**Comment by maxtoroq** [comment]
Perhaps if you change [this line](https://github.com/maxtoroq/sandcastle-md/blob/master/src/sandcastle-md/sandcastle-md.xsl#L251) to `1`.
